Lesson3
rateterin/geekshop pull request #3
Opened 2021-06-07 14:20 UTC by rateterin

2021-06-07 14:58 UTC, Vokler requested changes

2021-06-07 14:58 UTC, Vokler commented on products/views.py
> +        products = Product.objects.all()
Добавьте сюда еще вывод категорий

2021-06-07 17:19 UTC, rateterin commented on products/views.py
> +        products = Product.objects.all()
Имеете в виду вывод отфильтрованных по категории товаров при клике на категорию?

2021-06-08 07:12 UTC, Vokler commented on products/views.py
> +        products = Product.objects.all()
Нет, я имею в виду добавить еще работу с категориями:
1. Подтянуть с БД все категории
2. Передать в контекст
3. Вывести в products.html

2021-06-08 07:12 UTC, merged

2021-06-08 09:27 UTC, rateterin commented on products/views.py
> +        products = Product.objects.all()
Добавил. При клике на категорию в боковом меню она выделяется, а товары выводятся отфильтрованными по этой категории (только товары из этой категории), если товаров нет - выводится соответствующее сообщение.

По какой-то причине изменения в шаблонах не уходят в гитхаб. хоть задобавляйся их git add`ом.